services:
  db:
    image: postgres:latest
    container_name: monorepo-db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monorepo-test
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
